alias cw='cd ~/catkin_ws/'
alias cmd='catkin_make'
alias ros='roscore'
alias qt='sudo qtcreator'
alias bash='sudo gedit .bashrc'
alias laser='roslaunch lowerbodycore laser.launch'
alias hectorrec='roslaunch managment hector_slamrec.launch'
alias core='roslaunch lowerbodycore core.launch'
alias core2='roslaunch lowerbodycore core2.launch'
alias core3='rosrun upperbodycore upperbodycore'
alias hectormain='roslaunch managment hector_slam.launch'
alias hectorcalib='roslaunch managment hector_calib.launch'
alias move='roslaunch managment move_base.launch'
alias sepantamove='rosrun sepantamovebase sepantamovebase'
alias kinect='roslaunch freenect_launch freenect.launch'
alias tcp='rosrun tcpip core_tcp'
alias gui='mono catkin_ws/src/Sepanta3/GUI/sepanta_gui/main/main/obj/Debug/main.exe'
alias sim='roslaunch youbot_gazebo_robot youbot_base_only.launch'
alias objecttrain='rosrun object_recognition train_objects'
alias object='rosrun object_recognition object_recognition'
alias cmr='catkin_make -DCMAKE_BUILD_TYPE=Release'
alias scenario='rosrun sepantascenario scenario1'
alias objviz='rosrun object_recognition visualize_objects'
alias manager='rosrun managment managment'
alias joy='roslaunch lowerbodycore joy.launch'
alias motor1='roslaunch dynamixel_tutorials controller_manager.launch'
alias motor2='roslaunch dynamixel_tutorials controller_spawner.launch'

