alias kinect="roslaunch freenect_launch freenect.launch depth_registration:=true"
alias cm="catkin_make"
alias nkhVPN="sudo sshuttle -r sleptstar@ssh.alwaysdata.com 0/0"
alias qt="sh /opt/qtcreator-2.7.2/bin/qtcreator.sh"
alias st="rosrun icp_package tracker"
alias kt="killall tracker"
alias bash="sudo gedit .bashrc"
alias core="roslaunch lowerbodycore core.launch"
alias laser="roslaunch lowerbodycore laser.launch"
alias ros="roscore"
alias hectorrec="roslaunch managment hector_slamrec.launch"
alias hectormain="roslaunch managment hector_slam.launch"
alias move="roslaunch managment move_base.launch"
alias sepantamove="rosrun sepantamovebase sepantamovebase"
alias tcp="rosrun tcpip core_tcp"
alias gui="mono ~/catkin_ws/src/Sepanta3.1/GUI/sepanta_gui/main/main/obj/Debug/main.exe"
alias sim="roslaunch youbot_gazebo_robot youbot_base_only.launch"

