right1_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: right1
    joint_speed: 15

    motor:
        id: 1
        init: 2048
        min: 17
        max: 4096

right2_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: right2
    joint_speed: 15

    motor:
        id: 2
        init: 2048
        min: 17    
        max: 4096

right3_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: right3
    joint_speed: 15

    motor:
        id: 3
        init: 2048
        min: 740
        max: 4096

right4_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: rights4
    joint_speed: 15

    motor:
        id: 4
        init: 2048
        min: 0
        max: 4096

right5_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: right5
    joint_speed: 15

    motor:
        id: 5
        init: 2048
        min: 0
        max: 4096

right6_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: right6
    joint_speed: 15

    motor:
        id: 6
        init: 2048
        min: 0
        max: 4096

left1_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: left1
    joint_speed: 15

    motor:
        id: 11
        init: 2048
        min: 17
        max: 4096

left2_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: left2
    joint_speed: 15

    motor:
        id: 12
        init: 2048
        min: 17  
        max: 4096

left3_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: left3
    joint_speed: 15

    motor:
        id: 13
        init: 2048
        min: 435
        max: 4096

left4_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: left4
    joint_speed: 15

    motor:
        id: 14
        init: 996
        min: 350
        max: 1900

left5_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: left5
    joint_speed: 15

    motor:
        id: 15
        init: 50
        min: 10
        max: 500

left6_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: left6
    joint_speed: 15

    motor:
        id: 16
        init: 50
        min: 10
        max: 500
        
headYaw_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: headYaw
    joint_speed: 15

    motor:
        id: 20
        init: 500
        min: 400
        max: 600

headPitch_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: headPitch
    joint_speed: 15

    motor:
        id: 21
        init: 2996
        min: 2593
        max: 3391




