right1_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: right1
    joint_speed: 15

    motor:
        id: 1
        init: 3058
        min: 2126
        max: 3266

right2_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: right2
    joint_speed: 15

    motor:
        id: 2
        init: 1072
        min: 912    
        max: 2930

right3_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: right3
    joint_speed: 15

    motor:
        id: 3
        init: 4040
        min: 1470
        max: 2600

right4_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: rights4
    joint_speed: 15

    motor:
        id: 4
        init: 996
        min: 350
        max: 1900

right5_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: right5
    joint_speed: 15

    motor:
        id: 5
        init: 50
        min: 10
        max: 500

right6_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: right6
    joint_speed: 15

    motor:
        id: 6
        init: 50
        min: 10
        max: 500

left1_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: left1
    joint_speed: 15

    motor:
        id: 7
        init: 3058
        min: 2126
        max: 3266

left2_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: left2
    joint_speed: 15

    motor:
        id: 8
        init: 1072
        min: 912    
        max: 2930

left3_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: left3
    joint_speed: 15

    motor:
        id: 9
        init: 4040
        min: 1470
        max: 2600

left4_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: left4
    joint_speed: 15

    motor:
        id: 10
        init: 996
        min: 350
        max: 1900

left5_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: left5
    joint_speed: 15

    motor:
        id: 11
        init: 50
        min: 10
        max: 500

left6_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: left6
    joint_speed: 15

    motor:
        id: 12
        init: 50
        min: 10
        max: 500
        
headYaw_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: headYaw
    joint_speed: 15

    motor:
        id: 13
        init: 500
        min: 400
        max: 600

headPitch_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: headPitch
    joint_speed: 15

    motor:
        id: 14
        init: 2996
        min: 2593
        max: 3391




